# Generated by Django 3.2.19 on 2023-07-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_book_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
