# Generated by Django 3.2.19 on 2023-07-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_book_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
